package javaapplication1;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fahmi
 */
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    
    public ADMIN() {
        initComponents();
        labelanalisa.setVisible(false);
        labelpasien.setVisible(false);
        LOGOUT.setVisible(false);
        ketHelp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ketHelp = new javax.swing.JLabel();
        labelpasien = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();
        labelanalisa = new javax.swing.JLabel();
        tambah_pasien = new javax.swing.JLabel();
        analisa_penyakit = new javax.swing.JLabel();
        akun = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(650, 10, 30, 40);

        ketHelp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ketHelp.setForeground(new java.awt.Color(51, 51, 255));
        ketHelp.setText("bantuan");
        ketHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ketHelpMouseEntered(evt);
            }
        });
        getContentPane().add(ketHelp);
        ketHelp.setBounds(650, 50, 60, 13);

        labelpasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/tambah pasien ket.png"))); // NOI18N
        getContentPane().add(labelpasien);
        labelpasien.setBounds(0, 400, 800, 30);

        LOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/LOGOUT.png"))); // NOI18N
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUTMouseExited(evt);
            }
        });
        getContentPane().add(LOGOUT);
        LOGOUT.setBounds(700, 50, 80, 40);

        labelanalisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/analisa penyakit ket.png"))); // NOI18N
        getContentPane().add(labelanalisa);
        labelanalisa.setBounds(0, 400, 800, 30);

        tambah_pasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/tambah pasien.png"))); // NOI18N
        tambah_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah_pasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambah_pasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambah_pasienMouseExited(evt);
            }
        });
        getContentPane().add(tambah_pasien);
        tambah_pasien.setBounds(240, 250, 340, 40);

        analisa_penyakit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/analisa penyakit.png"))); // NOI18N
        analisa_penyakit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analisa_penyakitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                analisa_penyakitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                analisa_penyakitMouseExited(evt);
            }
        });
        getContentPane().add(analisa_penyakit);
        analisa_penyakit.setBounds(240, 180, 330, 50);

        akun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/admin.png"))); // NOI18N
        akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                akunMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                akunMouseExited(evt);
            }
        });
        getContentPane().add(akun);
        akun.setBounds(700, 20, 85, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/HOME APP.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 430);

        setSize(new java.awt.Dimension(800, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void analisa_penyakitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analisa_penyakitMouseEntered
        // TODO add your handling code here:
        labelanalisa.setVisible(true);
    }//GEN-LAST:event_analisa_penyakitMouseEntered

    private void analisa_penyakitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analisa_penyakitMouseExited
        // TODO add your handling code here:
        labelanalisa.setVisible(false);
    }//GEN-LAST:event_analisa_penyakitMouseExited

    private void tambah_pasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_pasienMouseEntered
        // TODO add your handling code here:
        labelpasien.setVisible(true);
    }//GEN-LAST:event_tambah_pasienMouseEntered

    private void tambah_pasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_pasienMouseExited
        // TODO add your handling code here:
        labelpasien.setVisible(false);
    }//GEN-LAST:event_tambah_pasienMouseExited

    private void LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        this.dispose();
           
    }//GEN-LAST:event_LOGOUTMouseClicked

    private void akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunMouseClicked
        // TODO add your handling code here:
        LOGOUT.setVisible(true);
    }//GEN-LAST:event_akunMouseClicked

    private void akunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_akunMouseExited

    private void analisa_penyakitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analisa_penyakitMouseClicked
        // TODO add your handling code here:
        new PasienInput().show();
        this.dispose();
    }//GEN-LAST:event_analisa_penyakitMouseClicked

    private void tambah_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_pasienMouseClicked
        // TODO add your handling code here:
        new BIODATA().show();
        this.dispose();
    }//GEN-LAST:event_tambah_pasienMouseClicked

    private void LOGOUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseExited
        // TODO add your handling code here:
       LOGOUT.setVisible(false);
    }//GEN-LAST:event_LOGOUTMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon ("src/bantuan/menu admin t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void ketHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ketHelpMouseEntered
        // TODO add your handling code here:
//        ketHelp.setVisible(true);
    }//GEN-LAST:event_ketHelpMouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        ketHelp.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        ketHelp.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel akun;
    private javax.swing.JLabel analisa_penyakit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ketHelp;
    private javax.swing.JLabel labelanalisa;
    private javax.swing.JLabel labelpasien;
    private javax.swing.JLabel tambah_pasien;
    // End of variables declaration//GEN-END:variables
}
