package javaapplication1;

import MODEL.koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author fahmi
 */
public class BIODATA extends javax.swing.JFrame {

    /**
     * Creates new form BIODATA
     */
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public static Long Nik;

    public BIODATA() {
        initComponents();
        error1.setVisible(false);
        error2.setVisible(false);
        error3.setVisible(false);
        error4.setVisible(false);
        error5.setVisible(false);
        error6.setVisible(false);
        error7.setVisible(false);
        ket1.setVisible(false);
        ket2.setVisible(false);
        ket3.setVisible(false);
        ket4.setVisible(false);
        ket5.setVisible(false);
        ket6.setVisible(false);
        ket7.setVisible(false);
        ketHelp.setVisible(false);

        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ketHelp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        ket1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        ket2 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();
        ket3 = new javax.swing.JLabel();
        error4 = new javax.swing.JLabel();
        ket4 = new javax.swing.JLabel();
        error5 = new javax.swing.JLabel();
        ket5 = new javax.swing.JLabel();
        error6 = new javax.swing.JLabel();
        ket6 = new javax.swing.JLabel();
        error7 = new javax.swing.JLabel();
        ket7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        JK = new javax.swing.JComboBox<>();
        Name = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        umur = new javax.swing.JTextField();
        Telp = new javax.swing.JTextField();
        goldar = new javax.swing.JTextField();
        simpan = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id_pasien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        ketHelp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ketHelp.setForeground(new java.awt.Color(0, 102, 204));
        ketHelp.setText("bantuan");
        getContentPane().add(ketHelp);
        ketHelp.setBounds(654, 50, 50, 13);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 10, 50, 40);

        error1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error1MouseExited(evt);
            }
        });
        getContentPane().add(error1);
        error1.setBounds(610, 170, 20, 20);

        ket1.setForeground(new java.awt.Color(153, 0, 0));
        ket1.setText("tidak boleh kosong");
        getContentPane().add(ket1);
        ket1.setBounds(640, 170, 150, 14);

        error2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error2MouseExited(evt);
            }
        });
        getContentPane().add(error2);
        error2.setBounds(610, 200, 20, 20);

        ket2.setForeground(new java.awt.Color(153, 0, 0));
        ket2.setText("tidak boleh kosong");
        getContentPane().add(ket2);
        ket2.setBounds(640, 200, 150, 14);

        error3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error3MouseExited(evt);
            }
        });
        getContentPane().add(error3);
        error3.setBounds(610, 230, 20, 20);

        ket3.setForeground(new java.awt.Color(153, 0, 0));
        ket3.setText("tidak boleh kosong");
        getContentPane().add(ket3);
        ket3.setBounds(640, 230, 150, 14);

        error4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error4MouseExited(evt);
            }
        });
        getContentPane().add(error4);
        error4.setBounds(400, 250, 20, 30);

        ket4.setForeground(new java.awt.Color(153, 0, 0));
        ket4.setText("tidak boleh kosong");
        getContentPane().add(ket4);
        ket4.setBounds(430, 260, 150, 14);

        error5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error5MouseExited(evt);
            }
        });
        getContentPane().add(error5);
        error5.setBounds(610, 290, 20, 20);

        ket5.setForeground(new java.awt.Color(153, 0, 0));
        ket5.setText("tidak boleh kosong");
        getContentPane().add(ket5);
        ket5.setBounds(640, 290, 150, 14);

        error6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error6MouseExited(evt);
            }
        });
        getContentPane().add(error6);
        error6.setBounds(610, 320, 20, 20);

        ket6.setForeground(new java.awt.Color(153, 0, 0));
        ket6.setText("tidak boleh kosong");
        getContentPane().add(ket6);
        ket6.setBounds(640, 320, 150, 14);

        error7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error7MouseExited(evt);
            }
        });
        getContentPane().add(error7);
        error7.setBounds(610, 350, 20, 20);

        ket7.setForeground(new java.awt.Color(153, 0, 0));
        ket7.setText("tidak boleh kosong");
        getContentPane().add(ket7);
        ket7.setBounds(640, 350, 150, 14);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/tambah pasien ref.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(220, 90, 360, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/logo kecil.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 260, 60);

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/admin.png"))); // NOI18N
        user.setText("jLabel4");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(700, 0, 90, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("NAMA PASIEN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 170, 80, 15);

        jLabel8.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel8.setText("NIK");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 190, 34, 20);

        jLabel9.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel9.setText("ALAMAT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 220, 60, 14);

        jLabel10.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel10.setText("JENIS KELAMIN");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 250, 90, 30);

        jLabel11.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel11.setText("UMUR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 290, 36, 16);

        jLabel12.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel12.setText("NO. TELPON");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 320, 80, 20);

        jLabel13.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel13.setText("GOL. DARAH");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 340, 80, 30);

        jLabel15.setText(":");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(220, 160, 20, 30);

        jLabel16.setText(":");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(220, 190, 20, 30);

        jLabel17.setText(":");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(220, 220, 20, 30);

        jLabel18.setText(":");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(220, 250, 20, 30);

        jLabel19.setText(":");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(230, 290, 0, 14);

        jLabel20.setText(":");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(220, 310, 20, 30);

        jLabel21.setText(":");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(220, 340, 20, 30);

        jLabel22.setText(":");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(220, 280, 20, 30);

        JK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih jenis kelamin", "laki-laki", "perempuan" }));
        getContentPane().add(JK);
        JK.setBounds(240, 250, 150, 30);

        Name.setBackground(new java.awt.Color(73, 88, 134));
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(240, 160, 370, 30);

        nik.setBackground(new java.awt.Color(73, 88, 134));
        nik.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nik);
        nik.setBounds(240, 190, 370, 30);

        alamat.setBackground(new java.awt.Color(73, 88, 134));
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alamat);
        alamat.setBounds(240, 220, 370, 30);

        umur.setBackground(new java.awt.Color(73, 88, 134));
        umur.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(umur);
        umur.setBounds(240, 280, 370, 30);

        Telp.setBackground(new java.awt.Color(73, 88, 134));
        Telp.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Telp);
        Telp.setBounds(240, 310, 370, 30);

        goldar.setBackground(new java.awt.Color(73, 88, 134));
        goldar.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(goldar);
        goldar.setBounds(240, 340, 370, 30);

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/simpan data.png"))); // NOI18N
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(610, 380, 140, 44);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/BACK.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(60, 110, 60, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/bg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 800, 440);
        getContentPane().add(id_pasien);
        id_pasien.setBounds(260, 140, 0, 0);

        setSize(new java.awt.Dimension(800, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
//        new POPUP().show();
//        this.dispose();
        SimpanData();
    }//GEN-LAST:event_simpanMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new ADMIN().show();
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void error1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error1MouseEntered
        // TODO add your handling code here:
        ket1.setVisible(true);
    }//GEN-LAST:event_error1MouseEntered

    private void error1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error1MouseExited
        // TODO add your handling code here:
        ket1.setVisible(false);
    }//GEN-LAST:event_error1MouseExited

    private void error2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error2MouseEntered
        // TODO add your handling code here:
        ket2.setVisible(true);
    }//GEN-LAST:event_error2MouseEntered

    private void error2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error2MouseExited
        // TODO add your handling code here:
        ket2.setVisible(false);
    }//GEN-LAST:event_error2MouseExited

    private void error3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error3MouseEntered
        // TODO add your handling code here:
        ket3.setVisible(true);
    }//GEN-LAST:event_error3MouseEntered

    private void error3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error3MouseExited
        // TODO add your handling code here:
        ket3.setVisible(false);
    }//GEN-LAST:event_error3MouseExited

    private void error4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error4MouseEntered
        // TODO add your handling code here:
        ket4.setVisible(true);
    }//GEN-LAST:event_error4MouseEntered

    private void error4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error4MouseExited
        // TODO add your handling code here:
        ket4.setVisible(false);
    }//GEN-LAST:event_error4MouseExited

    private void error5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error5MouseEntered
        // TODO add your handling code here:
        ket5.setVisible(true);
    }//GEN-LAST:event_error5MouseEntered

    private void error5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error5MouseExited
        // TODO add your handling code here:.
        ket5.setVisible(false);
    }//GEN-LAST:event_error5MouseExited

    private void error6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error6MouseEntered
        // TODO add your handling code here:
        ket6.setVisible(true);
    }//GEN-LAST:event_error6MouseEntered

    private void error6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error6MouseExited
        // TODO add your handling code here:
        ket6.setVisible(false);
    }//GEN-LAST:event_error6MouseExited

    private void error7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error7MouseEntered
        // TODO add your handling code here:
        ket7.setVisible(true);
    }//GEN-LAST:event_error7MouseEntered

    private void error7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error7MouseExited
        // TODO add your handling code here:
        ket7.setVisible(false);
    }//GEN-LAST:event_error7MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon("src/bantuan/biodata t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        ketHelp.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        ketHelp.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseExited

//     public void input(){
//        String Alamat = alamat.getText();
//        String Darah = goldar.getText();
//        String Nama = Name.getText();
//        String NIK = nik.getText();
//        String Telpon = Telp.getText();
//        String Umur = umur.getText();
//        
//        if (Alamat.equalsIgnoreCase("")||Darah.equalsIgnoreCase("")||Nama.equalsIgnoreCase("")||NIK.equalsIgnoreCase("")||
//                Telpon.equalsIgnoreCase("")||Umur.equalsIgnoreCase("")) {
//            JOptionPane.showMessageDialog(this, "Data Inputan Tidak Boleh Kosong!!");
//        }else{
//            new POPUP().show();
//        this.dispose();
//        }
//    }
    private void Nama() {
        int s1;
        if (Name.getText().length() == 0) {
            error1.setVisible(true);
            System.out.println("data nama kosong");
            s1 = 0;
        } else {
            error1.setVisible(false);
            System.out.println("data nama terisi");
            s1 = 1;
        }
    }

    private void NIK() {
        int s2;
        if (nik.getText().length() == 0) {
            error2.setVisible(true);
            System.out.println("data nik kosong");
            s2 = 0;
        } else {
            error2.setVisible(false);
            System.out.println("data nik terisi");
            s2 = 1;
        }
    }

    private void Alamat() {
        int s3;
        if (alamat.getText().length() == 0) {
            error3.setVisible(true);
            System.out.println("Data alamat kosong");
            s3 = 0;
        } else {
            error3.setVisible(false);
            System.out.println("data akamat terisi");
            s3 = 1;
        }
    }

    private void JenisKelamin() {
        int s4 = 0;
        if (JK.getSelectedItem().equals("laki-laki")) {
            System.out.println("laki-laki");
            error4.setVisible(false);
            s4 = 1;
        } else if (JK.getSelectedItem().equals("perempuan")) {
            System.out.println("perempuan");
            error4.setVisible(false);
            s4 = 2;
        } else {
            System.out.println("data kelami kosong");
            error4.setVisible(true);
            s4 = 0;
        }
    }

    private void Umur() {
        int s5;
        if (umur.getText().length() == 0) {
            error5.setVisible(true);
            System.out.println("Data umur kosong");
            s5 = 0;
        } else {
            error5.setVisible(false);
            System.out.println("data umur terisi");
            s5 = 1;
        }
    }

    private void telpon() {
        int s6;
        if (Telp.getText().length() == 0) {
            error6.setVisible(true);
            System.out.println("Data no. telp kosong");
            s6 = 0;
        } else {
            error6.setVisible(false);
            System.out.println("data no.telp terisi");
            s6 = 1;
        }
    }

    private void gol_darah() {
        int s7;
        if (goldar.getText().length() == 0) {
            error7.setVisible(true);
            System.out.println("data darah kosong");
            s7 = 0;
        } else {
            error6.setVisible(false);
            System.out.println("data darah terisi");
            s7 = 1;
        }

    }

    public void SimpanData() {
        Nama();
        NIK();
        Alamat();
        JenisKelamin();
        Umur();
        telpon();
        gol_darah();

//        if (Name.getText().length()>=1 && Name.getText().equals("a")) {
//            if (nik.getText().length()>=10) {
//                
//            }
//        }
        //tolong benerne. aku lali carane nyeluk variabel teko variabel metod lio
        if (Name.getText().length() > 1 && nik.getText().length() > 10 && alamat.getText().length() > 5 && umur.getText().length() >= 1 && Telp.getText().length() >= 6 && goldar.getText().length() >= 1) {
            if (JK.getSelectedItem().equals("laki-laki") || JK.getSelectedItem().equals("perempuan")) {

                int jawab = JOptionPane.showConfirmDialog(this, "Apakah yakin dengan data ini ?");
                switch (jawab) {
                    case JOptionPane.YES_OPTION:
                        simpan();
                        break;
                    case JOptionPane.NO_OPTION:
                        System.out.println("batal simpan");
                        new BIODATA().show();
                        dispose();
                        break;
                    case JOptionPane.CANCEL_OPTION:
                        System.out.println("cancel");
                }
            } else {
                JenisKelamin();
            }
        } else {
            JOptionPane.showMessageDialog(null, "lengkapi data dengan benar");
        }
    }

    private void simpan() {
        Random AngkaAcak = new Random();
        Nik = Long.parseLong(nik.getText());
        System.out.println(Nik);
        boolean databaru = true;
        if (databaru == true) { // prosess simpan atau edit
            try {
                sql = "insert into pasien values('" + AngkaAcak.nextInt(100) + "','" + JK.getSelectedItem() + "','" + goldar.getText() + "','" + Name.getText() + "','" + nik.getText() + "','" + alamat.getText() + "','" + umur.getText() + "','" + Telp.getText() + "')";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
//                    rs = stat.executeQuery(sql);
                JOptionPane.showMessageDialog(null, "data berhasil");
                System.out.println("data berhasil di input");
                new IDCARD().show();
                dispose();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "gagal input");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BIODATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BIODATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BIODATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BIODATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BIODATA().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JK;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Telp;
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel back;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel error4;
    private javax.swing.JLabel error5;
    private javax.swing.JLabel error6;
    private javax.swing.JLabel error7;
    private javax.swing.JTextField goldar;
    private javax.swing.JLabel id_pasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel ket1;
    private javax.swing.JLabel ket2;
    private javax.swing.JLabel ket3;
    private javax.swing.JLabel ket4;
    private javax.swing.JLabel ket5;
    private javax.swing.JLabel ket6;
    private javax.swing.JLabel ket7;
    private javax.swing.JLabel ketHelp;
    private javax.swing.JTextField nik;
    private javax.swing.JLabel simpan;
    private javax.swing.JTextField umur;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    
}
