/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import CONTROL.export;
import MODEL.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author fahmi
 */
public class cetakanalisa extends javax.swing.JFrame {

    /**
     * Creates new form cetakanalisa
     */
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

    private static int sakit;
    private static int riwayat;
    public static String hasilx;
    public static String gejalax;
    public static String pantanganx;

    public cetakanalisa() {
        initComponents();
        int id = new PasienInput().id;
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        ShowData();
        analisis1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ketHelp = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        Hasil = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Pantangan = new javax.swing.JLabel();
        Gejala = new javax.swing.JLabel();
        Penyakit3 = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        ketHelp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ketHelp.setForeground(new java.awt.Color(0, 102, 255));
        ketHelp.setText("Bantuan");
        getContentPane().add(ketHelp);
        ketHelp.setBounds(660, 50, 40, 14);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(660, 10, 40, 40);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/analisa penyakit ref.png"))); // NOI18N
        getContentPane().add(jLabel32);
        jLabel32.setBounds(210, 80, 380, 70);

        jLabel4.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel4.setText("ALAMAT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 210, 60, 20);

        jLabel8.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel8.setText("HASIL ANALISIS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 290, 90, 16);

        jLabel7.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel7.setText("PANTANGAN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 370, 120, 16);

        jLabel5.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel5.setText("GEJALA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 330, 120, 16);

        jLabel3.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel3.setText("ID PASIEN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 184, 60, 20);

        jLabel2.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel2.setText("NAMA PASIEN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 150, 80, 40);

        jLabel9.setText(":");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 160, 10, 20);

        jLabel10.setText(":");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 180, 10, 30);

        jLabel11.setText(":");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 210, 10, 14);

        jLabel12.setText(":");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(210, 330, 10, 14);

        jLabel14.setText(":");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(210, 370, 10, 20);

        jLabel15.setText(":");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(210, 290, 10, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/logo kecil.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 20, 260, 50);

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/admin.png"))); // NOI18N
        admin.setText("jLabel18");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        getContentPane().add(admin);
        admin.setBounds(700, 20, 90, 40);

        Hasil.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        getContentPane().add(Hasil);
        Hasil.setBounds(220, 290, 280, 20);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/garis.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(60, 270, 670, 14);

        Pantangan.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        getContentPane().add(Pantangan);
        Pantangan.setBounds(220, 370, 290, 30);

        Gejala.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        getContentPane().add(Gejala);
        Gejala.setBounds(220, 330, 290, 20);
        getContentPane().add(Penyakit3);
        Penyakit3.setBounds(220, 300, 220, 0);

        Alamat.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        getContentPane().add(Alamat);
        Alamat.setBounds(220, 210, 220, 20);

        Id.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        getContentPane().add(Id);
        Id.setBounds(220, 180, 50, 30);

        Nama.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        getContentPane().add(Nama);
        Nama.setBounds(220, 160, 220, 20);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/cancel.png"))); // NOI18N
        cancel.setText("jLabel30");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(570, 390, 100, 30);

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/print.png"))); // NOI18N
        print.setText("jLabel31");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(670, 390, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/BACKGROUND.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 430);

        setSize(new java.awt.Dimension(800, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        this.dispose();
    }//GEN-LAST:event_adminMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        new AnalisaPenyakit().show();
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
        
        
        try {
            boolean cetax = true;
            if (cetax==true) {
                CONTROL.cetakanalisa cetak = new CONTROL.cetakanalisa();
                cetak.print();
                JOptionPane.showMessageDialog(null, "data telah disimpan");
                new AnalisaPenyakit().show();
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "data gagal");
            }
        } catch (Exception e) {
        }
        
        
//        try{
//            boolean databaru = true;
//        if (databaru == true) { // prosess simpan atau edit
//            CONTROL.PrintIDCard cetak = new CONTROL.PrintIDCard();
//            cetak.print();
//            JOptionPane.showMessageDialog(null, "Data Telah di Cetak");
//        } else {
//            JOptionPane.showMessageDialog(null, "Gagal Cetak Data");
//        }
//        }catch(Exception e){
//            
//        }
//        new BIODATA().show();
//        dispose();
    }//GEN-LAST:event_printMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon("src/bantuan/cetak analisa t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
        ketHelp.setVisible(true);
    }//GEN-LAST:event_jLabel17MouseEntered

    public void ShowData() {
        int id = new PasienInput().id;
        try {
            System.out.println("ID Cetak : " + id);
            sql = "select * from pasien where id_pasien='" + id + "'";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {

                System.out.println("while");
                Nama.setText(rs.getString("username"));
                System.out.println(rs.getString("username"));
                Id.setText(rs.getString("ID_pasien"));
                System.out.println(rs.getString("ID_pasien"));
                Alamat.setText(rs.getString("alamat"));
                System.out.println(rs.getString("alamat"));

            }

        } catch (SQLException e) {
            System.out.println("null");
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //mencari id_penyakit dari top 1 data penyakit pasien
    private void analisis1() {

        try {
            int id = new PasienInput().id;
            sql = "select * from penyakit_pasien where ID_pasien='" + id + "' order by ID_penyakit asc";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                sakit = Integer.parseInt(rs.getString("ID_penyakit"));
                System.out.println("Top 1 sakit by id :" + sakit);
                analisis2();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //mencari id_riwayat penyakit
    private void analisis2() {
        try {
            sql = "select * from penyakit where ID_penyakit='" + sakit + "'";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                riwayat = Integer.parseInt(rs.getString("riwayat"));
                System.out.println(riwayat);
                analisa3();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //menganalisa penyakit dari tabel penyakit
    private void analisa3() {
        try {
            sql = "select * from penyakit where ID_penyakit='" + riwayat + "'";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                Hasil.setText(rs.getString("nama_penyakit"));
                hasilx = String.valueOf(rs.getString("nama_penyakit"));
                Gejala.setText(rs.getString("Gejala"));
                gejalax = String.valueOf(rs.getString("Gejala"));
                Pantangan.setText(rs.getString("Pantangan"));
                pantanganx = String.valueOf(rs.getString("Pantangan"));
            }
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cetakanalisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cetakanalisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cetakanalisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cetakanalisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cetakanalisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Gejala;
    private javax.swing.JLabel Hasil;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Pantangan;
    private javax.swing.JLabel Penyakit3;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel ketHelp;
    private javax.swing.JLabel print;
    // End of variables declaration//GEN-END:variables
}
