/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import MODEL.koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author fahmi
 */
public class EditPenyakit extends javax.swing.JFrame {

    /**
     * Creates new form EditPenyakit
     */
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public EditPenyakit() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        dataFromDataBaseToComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        simpan = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        riwayatObat = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        ID_Penyakit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        obat = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pantangan = new javax.swing.JTextField();
        gejala = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 40, 50, 40);

        jLabel19.setText(":");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(230, 240, 10, 30);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+1f));
        jLabel6.setText("NAMA PENYAKIT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 150, 100, 20);

        jLabel12.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel12.setText("OBAT");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 310, 80, 20);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/BACK.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(50, 110, 60, 30);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/Judul data penyakit.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(220, 90, 360, 40);

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/simpan data.png"))); // NOI18N
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(620, 380, 140, 44);

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/OPERATOR.png"))); // NOI18N
        user.setText("jLabel4");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(700, 0, 90, 60);

        riwayatObat.setBackground(new java.awt.Color(73, 88, 134));
        riwayatObat.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(riwayatObat);
        riwayatObat.setBounds(240, 240, 370, 30);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 210, 370, 30);
        getContentPane().add(ID_Penyakit);
        ID_Penyakit.setBounds(620, 210, 30, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("GEJALA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 180, 80, 15);

        jLabel8.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel8.setText("RIWAYAT PENYAKIT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 210, 120, 30);

        jLabel17.setText(":");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(230, 210, 30, 30);

        jLabel14.setText(":");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(230, 150, 10, 14);

        jLabel9.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel9.setText("RIWAYAT OBAT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 250, 100, 14);

        jLabel20.setText(":");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(230, 304, 10, 20);

        jLabel22.setText(":");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(230, 280, 10, 14);

        obat.setBackground(new java.awt.Color(73, 88, 134));
        obat.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(obat);
        obat.setBounds(240, 300, 370, 30);

        nama.setBackground(new java.awt.Color(73, 88, 134));
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        nama.setDoubleBuffered(true);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(240, 150, 370, 30);

        jLabel25.setText(":");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(230, 170, 30, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/logo kecil.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 260, 60);

        pantangan.setBackground(new java.awt.Color(73, 88, 134));
        pantangan.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pantangan);
        pantangan.setBounds(240, 270, 370, 30);

        gejala.setBackground(new java.awt.Color(73, 88, 134));
        gejala.setForeground(new java.awt.Color(255, 255, 255));
        gejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejalaActionPerformed(evt);
            }
        });
        getContentPane().add(gejala);
        gejala.setBounds(240, 180, 370, 30);

        jLabel11.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel11.setText("PANTANGAN");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 280, 72, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/bg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 800, 440);

        setSize(new java.awt.Dimension(800, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new RINCIANPENYAKIT ().show();
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
        ID();
        int jawab = JOptionPane.showConfirmDialog(this, "Apakah yakin dengan data ini ?");
                switch (jawab) {
                    case JOptionPane.YES_OPTION:
                        
                        simpan();
                        break;
                    case JOptionPane.NO_OPTION:
                        System.out.println("batal simpan");
                        new BIODATA().show();
                        dispose();
                        break;
                    case JOptionPane.CANCEL_OPTION:
                        System.out.println("cancel");
                }
        
        
//        new datapenyakit().show();
//        this.dispose();
    }//GEN-LAST:event_simpanMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void gejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejalaActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon ("src/bantuan/edit penyakit t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel3MouseClicked


    private void simpan(){
        Random AngkaAcak = new Random();
        
        boolean databaru = true;
        if (databaru == true) { // prosess simpan atau edit
            try {
                sql = "insert into penyakit values('" + AngkaAcak.nextInt(100) + "','" + nama.getText()+ "','" + gejala.getText() + "','" + ID_Penyakit.getText() + "','" + pantangan.getText() + "','" + riwayatObat.getText() + "','" + obat.getText() + "')";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
//                    rs = stat.executeQuery(sql);
                JOptionPane.showMessageDialog(null, "data berhasil");
                System.out.println("data berhasil di input");
                new datapenyakit().show();
                dispose();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "gagal input");
        }
    }
    private void dataFromDataBaseToComboBox(){
        try {
            sql="select * from penyakit";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {                
                jComboBox1.addItem(rs.getString("nama_penyakit"));
                
            }
             
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void ID(){
        try {
            sql = "SELECT * FROM penyakit WHERE nama_penyakit='"+jComboBox1.getSelectedItem()+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                ID_Penyakit.setText(rs.getString("ID_penyakit"));
                System.out.println(ID_Penyakit.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPenyakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_Penyakit;
    private javax.swing.JLabel back;
    private javax.swing.JTextField gejala;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField obat;
    private javax.swing.JTextField pantangan;
    private javax.swing.JTextField riwayatObat;
    private javax.swing.JLabel simpan;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
