/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import MODEL.koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author fahmi
 */
public class IDCARD extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form IDCARD
     */
    public IDCARD() {
        
        initComponents();
        ketHelp.setVisible(false);
        
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        Long NIK = new BIODATA().Nik;
        akun();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ketHelp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namapasien = new javax.swing.JTextField();
        id_pasien = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        cancel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        ketHelp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ketHelp.setForeground(new java.awt.Color(0, 102, 204));
        ketHelp.setText("Bantuan");
        getContentPane().add(ketHelp);
        ketHelp.setBounds(660, 40, 40, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 0, 40, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/tambah pasien ref.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 90, 360, 40);

        jLabel15.setText(":");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(240, 220, 10, 20);

        jLabel14.setText(":");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(240, 190, 10, 14);

        jLabel16.setText(":");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(240, 250, 4, 20);

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/print.png"))); // NOI18N
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(670, 370, 90, 50);

        jLabel9.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel9.setText("ALAMAT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 250, 60, 14);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+1f));
        jLabel6.setText("ID PASIEN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 190, 70, 20);

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/admin.png"))); // NOI18N
        user.setText("jLabel4");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(700, 0, 90, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/logo kecil.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 260, 60);

        namapasien.setBackground(new java.awt.Color(73, 88, 134));
        namapasien.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        namapasien.setForeground(new java.awt.Color(255, 255, 255));
        namapasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapasienActionPerformed(evt);
            }
        });
        getContentPane().add(namapasien);
        namapasien.setBounds(260, 220, 370, 22);

        id_pasien.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        getContentPane().add(id_pasien);
        id_pasien.setBounds(260, 190, 90, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("NAMA PASIEN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 220, 80, 20);

        alamat.setBackground(new java.awt.Color(73, 88, 134));
        alamat.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat);
        alamat.setBounds(260, 250, 370, 22);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/cancel.png"))); // NOI18N
        cancel.setText("jLabel8");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(580, 370, 110, 49);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/bg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 800, 440);
        getContentPane().add(nik);
        nik.setBounds(820, 140, 20, 20);

        setSize(new java.awt.Dimension(800, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namapasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapasienActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        new BIODATA().show();
        dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
        try{
            boolean databaru = true;
        if (databaru == true) { // prosess simpan atau edit
            CONTROL.PrintIDCard cetak = new CONTROL.PrintIDCard();
            cetak.print();
            JOptionPane.showMessageDialog(null, "Data Telah di Cetak");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal Cetak Data");
        }
        }catch(Exception e){
            
        }
        new BIODATA().show();
        dispose();
    }//GEN-LAST:event_printMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        dispose();
    }//GEN-LAST:event_userMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon ("src/bantuan/ID Card t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        ketHelp.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        ketHelp.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseExited

    public void akun(){
//        String a;
        BIODATA bio = new BIODATA();
        Long Nik = new BIODATA().Nik;
        System.out.println(Nik);
        try {
            sql="select * from pasien where nik='"+Nik+"'";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            System.out.println("try");
            while (rs.next()) {                
                System.out.println("while");
                id_pasien.setText(rs.getString("ID_pasien"));
//                a= rs.getString("ID_pasien");
                namapasien.setText(rs.getString("username"));
                System.out.println(rs.getString("username"));
                alamat.setText(rs.getString("alamat"));
                System.out.println(rs.getString("alamat"));
            }
             
        } catch (SQLException e) {
            System.out.println("null");
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public JTextField getNik() {
        return nik;
    }

    public void setNik(JTextField nik) {
        this.nik = nik;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDCARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDCARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDCARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDCARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDCARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel id_pasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel ketHelp;
    private javax.swing.JTextField namapasien;
    private javax.swing.JTextField nik;
    private javax.swing.JLabel print;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
