/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author EMIR
 */
public class operator extends javax.swing.JFrame {

    /**
     * Creates new form operator
     */
    public operator() {
        initComponents();
        labelpenyakit.setVisible(false);
        labelpasien.setVisible(false);
        logout.setVisible(false);
        labeluser.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeluser = new javax.swing.JLabel();
        datauser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelpasien = new javax.swing.JLabel();
        labelpenyakit = new javax.swing.JLabel();
        dta_pasien = new javax.swing.JLabel();
        data_penyakit = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 425));
        setUndecorated(true);
        getContentPane().setLayout(null);

        labeluser.setText("Data user digunakan untuk menambah, menghapus, melihat dan update akun untuk login user");
        getContentPane().add(labeluser);
        labeluser.setBounds(160, 400, 570, 14);

        datauser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/operator/tombol menu user.png"))); // NOI18N
        datauser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datauserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datauserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datauserMouseExited(evt);
            }
        });
        getContentPane().add(datauser);
        datauser.setBounds(250, 300, 330, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 0, 50, 50);

        labelpasien.setText("Data pasien digunakan ntuk melihat, menambah, merubah, dan menghapus data pasien");
        getContentPane().add(labelpasien);
        labelpasien.setBounds(180, 400, 510, 10);

        labelpenyakit.setText("Data penyakit digunakan untuk melihat, menambah, merubah, dan menghapus data penyakit");
        getContentPane().add(labelpenyakit);
        labelpenyakit.setBounds(170, 400, 540, 14);

        dta_pasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/Data Pasien.png"))); // NOI18N
        dta_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dta_pasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dta_pasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dta_pasienMouseExited(evt);
            }
        });
        getContentPane().add(dta_pasien);
        dta_pasien.setBounds(250, 240, 330, 50);

        data_penyakit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/Data Penyakit_2.png"))); // NOI18N
        data_penyakit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_penyakitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                data_penyakitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                data_penyakitMouseExited(evt);
            }
        });
        getContentPane().add(data_penyakit);
        data_penyakit.setBounds(250, 180, 330, 50);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/LOGOUT.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(700, 50, 90, 40);

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/OPERATOR.png"))); // NOI18N
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(690, 20, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/HOME APP.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 4, 800, 420);

        setSize(new java.awt.Dimension(807, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void data_penyakitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_penyakitMouseClicked
        // TODO add your handling code here:
        new datapenyakit().show();
        this.dispose();
    }//GEN-LAST:event_data_penyakitMouseClicked

    private void dta_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dta_pasienMouseClicked
        // TODO add your handling code here:
        new datapasien().show();
        this.dispose();
    }//GEN-LAST:event_dta_pasienMouseClicked

    private void data_penyakitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_penyakitMouseEntered
        // TODO add your handling code here:
        labelpenyakit.setVisible(true);
    }//GEN-LAST:event_data_penyakitMouseEntered

    private void data_penyakitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_penyakitMouseExited
        // TODO add your handling code here:
        labelpenyakit.setVisible(false);
    }//GEN-LAST:event_data_penyakitMouseExited

    private void dta_pasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dta_pasienMouseEntered
        // TODO add your handling code here:
        labelpasien.setVisible(true);
    }//GEN-LAST:event_dta_pasienMouseEntered

    private void dta_pasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dta_pasienMouseExited
        // TODO add your handling code here:
        labelpasien.setVisible(false);
    }//GEN-LAST:event_dta_pasienMouseExited

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        logout.setVisible(true);
    }//GEN-LAST:event_userMouseClicked

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setVisible(false);
    }//GEN-LAST:event_logoutMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon ("src/bantuan/menu operator t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void datauserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserMouseClicked
        // TODO add your handling code here:
        new DataAdmin().show();
        dispose();
    }//GEN-LAST:event_datauserMouseClicked

    private void datauserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserMouseEntered
        // TODO add your handling code here:
        labeluser.setVisible(true);
    }//GEN-LAST:event_datauserMouseEntered

    private void datauserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserMouseExited
        // TODO add your handling code here:
        labeluser.setVisible(false);
    }//GEN-LAST:event_datauserMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data_penyakit;
    private javax.swing.JLabel datauser;
    private javax.swing.JLabel dta_pasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelpasien;
    private javax.swing.JLabel labelpenyakit;
    private javax.swing.JLabel labeluser;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
