/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import MODEL.koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ImageIcon;
import CONTROL.PasienControl;

/**
 *
 * @author fahmi
 */
public class PasienInput extends javax.swing.JFrame {

    /**
     * Creates new form PasienInput
     */
    PasienControl pasien;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
public static int id;
    public PasienInput() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;

        ketHelp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ketHelp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        id_user = new javax.swing.JTextField();
        cari = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ketHelp.setForeground(new java.awt.Color(51, 102, 255));
        ketHelp.setText("bantuan");
        getContentPane().add(ketHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/BACK.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        nama.setBackground(new java.awt.Color(173, 39, 87));
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setBorder(null);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 170, 20));

        id_user.setBackground(new java.awt.Color(173, 39, 87));
        id_user.setForeground(new java.awt.Color(255, 255, 255));
        id_user.setBorder(null);
        getContentPane().add(id_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 170, 20));

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/SEARCH.png"))); // NOI18N
        cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariMouseClicked(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 190, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/pasien page.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariMouseClicked
        // TODO add your handling code here:
        System.out.println(id_user.getText());
        id = Integer.parseInt(id_user.getText());
        System.out.println(nama.getText());
        if (id_user.getText().length() == 0 || nama.getText().length() == 0) {
            System.out.println("data kosong");
            JOptionPane.showMessageDialog(null, "Masukkan data dengan lengkap");
        } else {
            try {
            sql = "SELECT * FROM pasien WHERE ID_pasien='"+id_user.getText()+"' AND username='"+nama.getText()+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                //System.out.println("next");
                if(id_user.getText().equals(rs.getString("ID_pasien")) && nama.getText().equals(rs.getString("username"))){
                    //System.out.println("");
                    //pasien.setId(id);
                    new AnalisaPenyakit().setVisible(true);
                    dispose();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "id pasien dan nama tidak singkron");
                }
            }else{
                JOptionPane.showMessageDialog(null, "pastikan data yang anda masukkan benar");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

        }

    }//GEN-LAST:event_cariMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new ADMIN().show();
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon("src/bantuan/pasien input t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        ketHelp.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        ketHelp.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseExited

    public int getId_user() {
        int id = Integer.parseInt(id_user.getText());
        return id;
    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasienInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasienInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasienInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasienInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PasienInput().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel cari;
    private javax.swing.JTextField id_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel ketHelp;
    private javax.swing.JTextField nama;
    // End of variables declaration//GEN-END:variables

    
}
