/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author fahmi
 */
public class POPUP extends javax.swing.JFrame {

    /**
     * Creates new form POPUP
     */
    public POPUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tidak = new javax.swing.JLabel();
        ya = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        tidak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/tidak.png"))); // NOI18N
        tidak.setText("jLabel25");
        tidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tidakMouseClicked(evt);
            }
        });
        getContentPane().add(tidak);
        tidak.setBounds(140, 110, 60, 30);

        ya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/ya.png"))); // NOI18N
        ya.setText("jLabel26");
        ya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yaMouseClicked(evt);
            }
        });
        getContentPane().add(ya);
        ya.setBounds(210, 110, 70, 30);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/dasar.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 0, 300, 180);

        jLabel19.setText(":");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(230, 290, 0, 14);

        jLabel33.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        getContentPane().add(jLabel33);
        jLabel33.setBounds(90, 210, 34, 20);

        jLabel44.setText(":");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(230, 290, 0, 14);

        setSize(new java.awt.Dimension(306, 186));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tidakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidakMouseClicked
        // TODO add your handling code here:
        new BIODATA().show();
        this.dispose();
    }//GEN-LAST:event_tidakMouseClicked

    private void yaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yaMouseClicked
        // TODO add your handling code here:
        new IDCARD().show();
        this.dispose();
    }//GEN-LAST:event_yaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POPUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel tidak;
    private javax.swing.JLabel ya;
    // End of variables declaration//GEN-END:variables
}
