/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author EMIR
 */
public class RINCIANPASIEN extends javax.swing.JFrame {

    /**
     * Creates new form RINCIANPASIEN
     */
    public RINCIANPASIEN() {
        initComponents();
        error1.setVisible(false);
        error2.setVisible(false);
        error3.setVisible(false);
        error4.setVisible(false);
        error5.setVisible(false);
        error6.setVisible(false);
        error7.setVisible(false);
        ket1.setVisible(false);
        ket2.setVisible(false);
        ket3.setVisible(false);
        ket4.setVisible(false);
        ket5.setVisible(false);
        ket6.setVisible(false);
        ket7.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        ket1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        ket2 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();
        ket3 = new javax.swing.JLabel();
        error4 = new javax.swing.JLabel();
        ket4 = new javax.swing.JLabel();
        error5 = new javax.swing.JLabel();
        ket5 = new javax.swing.JLabel();
        error6 = new javax.swing.JLabel();
        ket6 = new javax.swing.JLabel();
        error7 = new javax.swing.JLabel();
        ket7 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jk = new javax.swing.JRadioButton();
        jk2 = new javax.swing.JRadioButton();
        umur = new javax.swing.JTextField();
        Telp = new javax.swing.JTextField();
        goldar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        simpan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 425));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 40, 60, 40);

        error1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error1MouseExited(evt);
            }
        });
        getContentPane().add(error1);
        error1.setBounds(620, 180, 19, 20);

        ket1.setForeground(new java.awt.Color(204, 0, 0));
        ket1.setText("Data tidak boleh kosong");
        getContentPane().add(ket1);
        ket1.setBounds(650, 180, 150, 14);

        error2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error2MouseExited(evt);
            }
        });
        getContentPane().add(error2);
        error2.setBounds(620, 210, 20, 20);

        ket2.setForeground(new java.awt.Color(204, 0, 0));
        ket2.setText("Data tidak boleh kosong");
        getContentPane().add(ket2);
        ket2.setBounds(650, 210, 150, 14);

        error3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error3MouseExited(evt);
            }
        });
        getContentPane().add(error3);
        error3.setBounds(620, 240, 19, 16);

        ket3.setForeground(new java.awt.Color(204, 0, 0));
        ket3.setText("Data tidak boleh kosong");
        getContentPane().add(ket3);
        ket3.setBounds(650, 240, 150, 14);

        error4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error4MouseExited(evt);
            }
        });
        getContentPane().add(error4);
        error4.setBounds(390, 270, 20, 16);

        ket4.setForeground(new java.awt.Color(204, 0, 0));
        ket4.setText("Data tidak boleh kosong");
        getContentPane().add(ket4);
        ket4.setBounds(430, 270, 180, 14);

        error5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error5MouseExited(evt);
            }
        });
        getContentPane().add(error5);
        error5.setBounds(620, 290, 20, 16);

        ket5.setForeground(new java.awt.Color(204, 0, 0));
        ket5.setText("Data tidak boleh kosong");
        getContentPane().add(ket5);
        ket5.setBounds(650, 290, 150, 14);

        error6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error6MouseExited(evt);
            }
        });
        getContentPane().add(error6);
        error6.setBounds(620, 320, 20, 16);

        ket6.setForeground(new java.awt.Color(204, 0, 0));
        ket6.setText("Data tidak boleh kosong");
        getContentPane().add(ket6);
        ket6.setBounds(650, 320, 150, 14);

        error7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/unnamed.png"))); // NOI18N
        error7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                error7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                error7MouseExited(evt);
            }
        });
        getContentPane().add(error7);
        error7.setBounds(620, 350, 19, 16);

        ket7.setForeground(new java.awt.Color(204, 0, 0));
        ket7.setText("Data tidak boleh kosong");
        getContentPane().add(ket7);
        ket7.setBounds(650, 350, 150, 14);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/BACK.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(50, 110, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/logo kecil.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 260, 60);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/judul data pasien.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(220, 90, 360, 40);

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/OPERATOR.png"))); // NOI18N
        user.setText("jLabel4");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(690, 0, 100, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("NAMA PASIEN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 190, 80, 15);

        jLabel8.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel8.setText("NIK");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 210, 34, 20);

        jLabel9.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel9.setText("ALAMAT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 240, 60, 14);

        jLabel10.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel10.setText("JENIS KELAMIN");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 255, 90, 30);

        jLabel11.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel11.setText("UMUR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 290, 36, 16);

        jLabel12.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel12.setText("NO. TELPON");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 330, 80, 20);

        jLabel13.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel13.setText("GOL. DARAH");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 350, 80, 30);

        jLabel21.setText(":");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(230, 350, 4, 20);

        Name.setBackground(new java.awt.Color(73, 88, 134));
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(240, 180, 370, 30);

        nik.setBackground(new java.awt.Color(73, 88, 134));
        nik.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nik);
        nik.setBounds(240, 210, 370, 30);

        alamat.setBackground(new java.awt.Color(73, 88, 134));
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alamat);
        alamat.setBounds(240, 240, 370, 30);

        buttonGroup1.add(jk);
        jk.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jk.setText("PRIA");
        jk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkActionPerformed(evt);
            }
        });
        getContentPane().add(jk);
        jk.setBounds(240, 270, 70, 25);

        buttonGroup1.add(jk2);
        jk2.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jk2.setText("WANITA");
        getContentPane().add(jk2);
        jk2.setBounds(310, 270, 69, 25);

        umur.setBackground(new java.awt.Color(73, 88, 134));
        umur.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(umur);
        umur.setBounds(240, 290, 370, 30);

        Telp.setBackground(new java.awt.Color(73, 88, 134));
        Telp.setForeground(new java.awt.Color(255, 255, 255));
        Telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelpActionPerformed(evt);
            }
        });
        getContentPane().add(Telp);
        Telp.setBounds(240, 320, 370, 30);

        goldar.setBackground(new java.awt.Color(73, 88, 134));
        goldar.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(goldar);
        goldar.setBounds(240, 350, 370, 30);

        jLabel20.setText(":");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(230, 320, 10, 14);

        jLabel22.setText(":");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(230, 290, 10, 14);

        jLabel18.setText(":");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(230, 260, 10, 14);

        jLabel17.setText(":");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(230, 200, 30, 40);

        jLabel19.setText(":");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(230, 234, 4, 20);

        jLabel25.setText(":");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(230, 170, 30, 40);

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/simpan data.png"))); // NOI18N
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(620, 380, 140, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/bg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 800, 440);

        setSize(new java.awt.Dimension(800, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void jkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new datapasien().show();
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
//        new datapasien().show();
//        this.dispose();
        SimpanData();
    }//GEN-LAST:event_simpanMouseClicked

    private void error1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error1MouseEntered
        // TODO add your handling code here:
        ket1.setVisible(true);
    }//GEN-LAST:event_error1MouseEntered

    private void error1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error1MouseExited
        // TODO add your handling code here:
        ket1.setVisible(false);
    }//GEN-LAST:event_error1MouseExited

    private void TelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelpActionPerformed

    private void error2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error2MouseEntered
        // TODO add your handling code here:
        ket2.setVisible(true);
    }//GEN-LAST:event_error2MouseEntered

    private void error2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error2MouseExited
        // TODO add your handling code here:
        ket2.setVisible(false);
    }//GEN-LAST:event_error2MouseExited

    private void error3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error3MouseEntered
        // TODO add your handling code here:
        ket3.setVisible(true);
    }//GEN-LAST:event_error3MouseEntered

    private void error3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error3MouseExited
        // TODO add your handling code here:
        ket3.setVisible(false);
    }//GEN-LAST:event_error3MouseExited

    private void error4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error4MouseEntered
        // TODO add your handling code here:
        ket4.setVisible(true);
    }//GEN-LAST:event_error4MouseEntered

    private void error4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error4MouseExited
        // TODO add your handling code here:
        ket4.setVisible(false);
    }//GEN-LAST:event_error4MouseExited

    private void error5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error5MouseEntered
        // TODO add your handling code here:
        ket5.setVisible(true);
    }//GEN-LAST:event_error5MouseEntered

    private void error5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error5MouseExited
        // TODO add your handling code here:
        ket5.setVisible(false);
    }//GEN-LAST:event_error5MouseExited

    private void error6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error6MouseEntered
        // TODO add your handling code here:
        ket6.setVisible(true);
    }//GEN-LAST:event_error6MouseEntered

    private void error6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error6MouseExited
        // TODO add your handling code here:
        ket6.setVisible(false);
    }//GEN-LAST:event_error6MouseExited

    private void error7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error7MouseEntered
        // TODO add your handling code here:
        ket7.setVisible(true);
    }//GEN-LAST:event_error7MouseEntered

    private void error7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error7MouseExited
        // TODO add your handling code here:
        ket7.setVisible(false);
    }//GEN-LAST:event_error7MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon ("src/bantuan/rincian pasien t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel3MouseClicked

    int s1,s2,s3,s4,s5,s6,s7;
    private void Nama(){
        this.s1=s1;
        if (Name.getText().length()==0) {
            error1.setVisible(true);
            System.out.println("data nama kosong");
            s1=0;
            
        }if (Name.getText().length()>=1) {
            error1.setVisible(false);
            if (Name.getText().length()<3) {
                JOptionPane.showMessageDialog(null, "Isi nama dengan benar");
            }else {
                s1=1;
                SimpanData();
            }
        }else{
            Nama();
        }
    }
    private void NIK(){
        this.s2=s2;
        if (nik.getText().length()==0) {
            error2.setVisible(true);
            System.out.println("data nik kosong");
            s2=0;
        }if (nik.getText().length()>0) {
            error2.setVisible(false);
            if (nik.getText().length()<10) {
                JOptionPane.showMessageDialog(null, "Isi nik dengan benar");
            }else if (nik.getText().length()>=10) {
                SimpanData();
                s2=1;
            }
        }
    }
    private void Alamat(){
        this.s3= s3;
        if (alamat.getText().length()==0) {
            error3.setVisible(true);
            System.out.println("Data alamat kosong");
            s3=0;
        }if (alamat.getText().length()>0) {
            error3.setVisible(false);
            if (alamat.getText().length()<10) {
                JOptionPane.showMessageDialog(null, "Isi nama dengan benar");
            }else if (alamat.getText().length()>=10) {
                SimpanData();
                s3=1;
            }
        }
    }
    private void JenisKelamin(){
        this.s4= s4;
        if (jk.isSelected()) {
            System.out.println("laki-laki");
            error4.setVisible(false);
            s4=1;
        }else if (jk2.isSelected()) {
            System.out.println("perempuan");
            error4.setVisible(false);
            s4=1;
        }else{
            System.out.println("data kelami kosong");
            error4.setVisible(true);
            s4=0;
        }
    }
    private void Umur(){
        this.s5= s5;
        if (umur.getText().length()==0) {
            error5.setVisible(true);
            System.out.println("Data umur kosong");
            s5=0;
        }if (umur.getText().length()>0) {
            if (umur.getText().length()<3) {
                JOptionPane.showMessageDialog(null, "Isi nama dengan benar");
            }else if (umur.getText().length()>=3) {
                SimpanData();
                s5=1;
            }
        }
    }
    private void telp(){
        this.s6= s6;
        if (Telp.getText().length()==0) {
            error6.setVisible(true);
            System.out.println("Data no. telp kosong");
            s6=0;
        }if (Telp.getText().length()>0) {
            if (Telp.getText().length()<3) {
                JOptionPane.showMessageDialog(null, "Isi nama dengan benar");
            }else if (Telp.getText().length()>=3) {
                SimpanData();
                s6=1;
            }
        }
    }
    private void gol_darah(){
        this.s7= s7;
        if (goldar.getText().length()==0) {
            error7.setVisible(true);
            System.out.println("data darah kosong");
            s7=0;
        }if (goldar.getText().length()>0) {
            if (goldar.getText().length()<3) {
                JOptionPane.showMessageDialog(null, "Isi nama dengan benar");
            }else if (goldar.getText().length()>=3) {
                SimpanData();
                s7=1;
            }
        }
        
    }
    public void SimpanData(){      
        
        //cek kebenaran data
        if (Name.getText().length()>1 && nik.getText().length()>10 && alamat.getText().length()>5 && umur.getText().length()>=1 && Telp.getText().length()>=6 && goldar.getText().length()>=1) {
            if (jk.isSelected() || jk2.isSelected()) {
                
            
                int jawab = JOptionPane.showConfirmDialog(this, "Apakah yakin dengan data ini ?");
                switch (jawab){
                    case JOptionPane.YES_OPTION:
                        System.out.println("data berhasil disimpan");
                        JOptionPane.showMessageDialog(this, "data berhasil disimpan");
                        //tambahin input simpan data ke database
                        new IDCARD().show();
                        dispose();
                        break;
                    case JOptionPane.NO_OPTION:
                        System.out.println("batal simpan");
                        new BIODATA().show();
                        dispose();
                        break;
                    case JOptionPane.CANCEL_OPTION:
                        System.out.println("cancel");
                }
            }else{
                JenisKelamin();
            }
        }else{
            JOptionPane.showMessageDialog(null, "lengkapi data dengan benar");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RINCIANPASIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RINCIANPASIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RINCIANPASIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RINCIANPASIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RINCIANPASIEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Telp;
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel error4;
    private javax.swing.JLabel error5;
    private javax.swing.JLabel error6;
    private javax.swing.JLabel error7;
    private javax.swing.JTextField goldar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jk;
    private javax.swing.JRadioButton jk2;
    private javax.swing.JLabel ket1;
    private javax.swing.JLabel ket2;
    private javax.swing.JLabel ket3;
    private javax.swing.JLabel ket4;
    private javax.swing.JLabel ket5;
    private javax.swing.JLabel ket6;
    private javax.swing.JLabel ket7;
    private javax.swing.JTextField nik;
    private javax.swing.JLabel simpan;
    private javax.swing.JTextField umur;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
