/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author EMIR
 */
public class RINCIANPENYAKIT extends javax.swing.JFrame {

    /**
     * Creates new form RINCIANPENYAKIT
     */
    public RINCIANPENYAKIT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        akun = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kembali = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 425));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 50, 50, 40);

        jTextField2.setBackground(new java.awt.Color(73, 88, 134));
        jTextField2.setForeground(new java.awt.Color(73, 88, 134));
        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 210, 370, 20);

        jTextField3.setBackground(new java.awt.Color(73, 88, 134));
        jTextField3.setForeground(new java.awt.Color(73, 88, 134));
        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 260, 370, 20);

        jTextField1.setBackground(new java.awt.Color(73, 88, 134));
        jTextField1.setForeground(new java.awt.Color(73, 88, 134));
        jTextField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField1.setDoubleBuffered(true);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 150, 370, 20);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/edit rincian penyakit.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(640, 380, 28, 20);

        edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(640, 370, 100, 40);

        jLabel22.setText(":");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(230, 310, 10, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("GEJALA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 180, 80, 15);

        jLabel12.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel12.setText("OBAT");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 360, 80, 20);

        akun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/OPERATOR.png"))); // NOI18N
        akun.setText("jLabel4");
        akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                akunMouseClicked(evt);
            }
        });
        getContentPane().add(akun);
        akun.setBounds(700, 0, 90, 60);

        jLabel8.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel8.setText("RIWAYAT PENYAKIT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 210, 120, 20);

        jLabel19.setText(":");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(230, 260, 10, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/logo kecil.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 260, 60);

        jTextField4.setBackground(new java.awt.Color(73, 88, 134));
        jTextField4.setForeground(new java.awt.Color(73, 88, 134));
        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 310, 370, 20);

        jLabel14.setText(":");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(230, 150, 10, 14);

        jLabel25.setText(":");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(230, 170, 30, 40);

        jTextField5.setBackground(new java.awt.Color(73, 88, 134));
        jTextField5.setForeground(new java.awt.Color(73, 88, 134));
        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 350, 370, 20);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+1f));
        jLabel6.setText("NAMA PENYAKIT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 150, 100, 20);

        jLabel17.setText(":");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(230, 200, 30, 40);

        jLabel20.setText(":");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(230, 360, 10, 14);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/Judul data penyakit.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(220, 90, 360, 40);

        jLabel9.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel9.setText("RIWAYAT OBAT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 260, 100, 14);

        jLabel11.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel11.setText("PANTANGAN");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 310, 72, 16);

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/BACK.png"))); // NOI18N
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(kembali);
        kembali.setBounds(50, 110, 60, 30);

        jTextField7.setBackground(new java.awt.Color(73, 88, 134));
        jTextField7.setForeground(new java.awt.Color(73, 88, 134));
        jTextField7.setText("jTextField1");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(240, 180, 370, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/bg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 800, 440);

        setSize(new java.awt.Dimension(800, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        new datapenyakit().show();
        this.dispose();
    }//GEN-LAST:event_kembaliMouseClicked

    private void akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        this.dispose();
    }//GEN-LAST:event_akunMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon ("src/bantuan/rincian penyakit t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RINCIANPENYAKIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RINCIANPENYAKIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RINCIANPENYAKIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RINCIANPENYAKIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RINCIANPENYAKIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akun;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel kembali;
    // End of variables declaration//GEN-END:variables
}
