/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import MODEL.koneksi;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import static javaapplication1.LoginAdmin.generatedPassword;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TambahAdmin extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

    public static String generatedPassword;
    /**
     * Creates new form TambahAdmin
     */
    public TambahAdmin() {
        initComponents();
        //error.setVisible(false);
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahdata = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        operator = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/tambah data.png"))); // NOI18N
        tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahdataMouseClicked(evt);
            }
        });
        getContentPane().add(tambahdata);
        tambahdata.setBounds(550, 260, 220, 70);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/cancel.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(470, 270, 100, 40);

        operator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/OPERATOR.png"))); // NOI18N
        operator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operatorMouseClicked(evt);
            }
        });
        getContentPane().add(operator);
        operator.setBounds(690, 20, 100, 30);

        password.setBackground(new java.awt.Color(234, 240, 240));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(300, 210, 400, 20);

        username.setBackground(new java.awt.Color(232, 239, 239));
        getContentPane().add(username);
        username.setBounds(300, 180, 410, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/operator/tambah user.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 425);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 290, 34, 14);

        setSize(new java.awt.Dimension(816, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void operatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatorMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        dispose();
    }//GEN-LAST:event_operatorMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        new DataAdmin().show();
        dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahdataMouseClicked
        // TODO add your handling code here:
        encrypt();
    }//GEN-LAST:event_tambahdataMouseClicked
    public void Tambah() {
        Random AngkaAcak = new Random();
        try {
            sql = "insert into login values('"+AngkaAcak.nextInt(100)+"','" + username.getText() + "','" + generatedPassword + "','1')";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "berhasil ditambahkan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void encrypt(){
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
         
            md.update(password.getText().getBytes());
        
            byte[] bytes = md.digest();
         
            StringBuilder sb = new StringBuilder();
            for(int i=0; i< bytes.length ;i++)
            {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
         
            generatedPassword = sb.toString();
            Tambah();

        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel operator;
    private javax.swing.JTextField password;
    private javax.swing.JLabel tambahdata;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
