/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import MODEL.koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.Date;  
import java.text.DateFormat;  
import java.text.SimpleDateFormat;
import java.util.Random;

/**
 *
 * @author fahmi
 */
public class TambahPenyakit extends javax.swing.JFrame {

    /**
     * Creates new form TambahPenyakit
     */
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public TambahPenyakit() {
        initComponents();
        ketHelp.setVisible(false);
        int id = new PasienInput().id;
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        dataFromDataBaseToComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_Penyakit = new javax.swing.JTextField();
        ketHelp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        tambahdata = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        ID_Penyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_PenyakitActionPerformed(evt);
            }
        });
        getContentPane().add(ID_Penyakit);
        ID_Penyakit.setBounds(270, 250, 90, 30);

        ketHelp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ketHelp.setForeground(new java.awt.Color(0, 102, 204));
        ketHelp.setText("Bantuan");
        getContentPane().add(ketHelp);
        ketHelp.setBounds(660, 40, 40, 13);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bantuan/help.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 0, 50, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/analisa penyakit ref.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 80, 363, 70);

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(270, 200, 400, 40);

        tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/tambah data.png"))); // NOI18N
        tambahdata.setText("jLabel10");
        tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahdataMouseClicked(evt);
            }
        });
        getContentPane().add(tambahdata);
        tambahdata.setBounds(490, 330, 180, 40);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/cancel.png"))); // NOI18N
        cancel.setText("jLabel9");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(410, 320, 100, 60);

        jLabel6.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        jLabel6.setText("NAMA PENYAKIT     :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 210, 150, 19);

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/admin.png"))); // NOI18N
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(700, 10, 85, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/logo kecil.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 260, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/foto/BACKGROUND.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 425);

        setSize(new java.awt.Dimension(800, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        new AnalisaPenyakit().show();
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        new LoginAdmin().show();
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahdataMouseClicked
        // TODO add your handling code here:
        ID();
        TambahPenyakit();
    }//GEN-LAST:event_tambahdataMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ImageIcon help = new ImageIcon ("src/bantuan/tambah penyakit t.png");
        JOptionPane.showMessageDialog(null, " ", " ", JOptionPane.INFORMATION_MESSAGE, help);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        ketHelp.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        ketHelp.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseExited

    private void ID_PenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_PenyakitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_PenyakitActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    public void TambahPenyakit(){
        Random AngkaAcak = new Random();
        int id = new PasienInput().id;
        boolean databaru = true;
        if (databaru == true) { // prosess simpan atau edit
            try {
                System.out.println("random angka : "+AngkaAcak.nextInt(100));
                System.out.println("id : "+ id);
                System.out.println("ID Penyakit : "+ID_Penyakit.getText());
                sql = "insert into penyakit_pasien values('"+AngkaAcak.nextInt(100)+"','"+id+"','"+ID_Penyakit.getText()+"','"+getTanggal()+"');";
                System.out.println("Tanggal : "+getTanggal());
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
//                rs = stat.executeQuery(sql);
                JOptionPane.showMessageDialog(null, "data berhasil");
                System.out.println("data berhasil di input");
                
                new AnalisaPenyakit().show();
                dispose();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println("ada yang error");
            }
        } else {
            JOptionPane.showMessageDialog(null, "gagal input");
        }
    }
    
    private void dataFromDataBaseToComboBox(){
        try {
            sql="select * from penyakit";
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next()) {                
                jComboBox1.addItem(rs.getString("nama_penyakit"));
                
            }
             
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void ID(){
        try {
            sql = "SELECT * FROM penyakit WHERE nama_penyakit='"+jComboBox1.getSelectedItem()+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                ID_Penyakit.setText(rs.getString("ID_penyakit"));
                System.out.println(ID_Penyakit.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private String getTanggal() {  
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");  
        Date date = new Date();  
        return dateFormat.format(date);  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPenyakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_Penyakit;
    private javax.swing.JLabel cancel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel ketHelp;
    private javax.swing.JLabel tambahdata;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
